bbs/s10day12bbs/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from bbs import views
from webqq import urls as chat_urls
urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^chat/', include(chat_urls)),
    url(r'^$', views.index ),
    url(r'^life/$', views.life, name='life' ),
    url(r'^tech/$', views.tech, name='tech' ),
    url(r'^1024/$', views.category1024, name='category1024' ),
    url(r'^login/$', views.account_login, name='login'),
    url(r'^article/(\d+)/$', views.article, name='article'),
    url(r'^article/create/$', views.create_article, name='create_article'),

]

bbs/webqq/urls.py
from django.conf.urls import include, url

import views
urlpatterns = [
    url(r'^$', views.dashboard,name='chat'),
    url(r'^send_msg/$', views.send_msg, name='chat_send_msg'),
    url(r'^get_msg/$', views.get_msg, name='get_new_msg'),
]

bbs/bbs/models.py
#coding:utf-8
from django.db import models
from django.contrib.auth.models import User
# Create your models here.
class Article(models.Model): #创建文章表
    title = models.CharField(max_length=254) #帖子名称，可以重名
    category = models.ForeignKey('Category') #板块表
    content = models.TextField(max_length=100000) #帖子内容，使用textfield，因为文字很多
    author = models.ForeignKey('UserProfile') #作者，外键关联到UserProfile
    summary = models.TextField(max_length=500) #简介
    head_img = models.ImageField(upload_to="statics/imgs/upload") #头部配图
    publish_date = models.DateTimeField(auto_now_add=True) #日期，auto_now_add=True自动生成
    #thumb_ups = models.ForeignKey("ThumbUp",blank=True) #点赞，blank=True不是必须的，由于是一个文章需要多个点赞，因此需要单独列出一个点赞表，反向外键关联到文章表上
    #comments = models.ManyToManyField("Comment",blank=True) #评论表
    def __unicode__(self):
        return self.title

class Category(models.Model): #板块表
    name = models.CharField(unique=True,max_length=64) #板块名，unique=True不能重复
    admins = models.ManyToManyField('UserProfile')  #版主
    def __unicode__(self):
        return self.name
class ThumbUp(models.Model): #点赞表
    article = models.ForeignKey('Article') #文章表，外键反关联到Aritcle表中
    user = models.ForeignKey('UserProfile') #谁点的赞
    date = models.DateTimeField(auto_now_add=True) #日期
    def __unicode__(self):
        return self.article.title

class Comment(models.Model): #评论表
    article = models.ForeignKey('Article') #标题
    user = models.ForeignKey('UserProfile') #用户
    #特别注意，如果做自关联时候，必须要用related_name
    parent_comment = models.ForeignKey('self',blank=True,null=True,related_name='pid') #父级评论（自己关联自己），blank=True可以为空（admin页面可以为空），null=True数据库中可以为空
    comment = models.TextField(max_length=1024) #评论内容
    date = models.DateTimeField(auto_now_add=True) #评论时间
    def __unicode__(self):
        return  self.comment

class UserProfile(models.Model):  #用户信息表
    user = models.OneToOneField(User) #用户
    name = models.CharField(max_length=32) #中文名
    user_groups = models.ManyToManyField('UserGroup') #用户组
    friends = models.ManyToManyField('self',blank=True,related_name='my_friends') #好友
    def __unicode__(self):
        return self.name

class UserGroup(models.Model): #用户组表
    name = models.CharField(max_length=32,unique=True) #组名，unique=True不能重复
    def __unicode__(self):
        return self.name

bbs/webqq/models.py
#coding:utf-8
from django.db import models
from bbs import models as bbs_models
# Create your models here.


class QQGroup(models.Model):
    name = models.CharField(max_length=64)
    founder = models.ForeignKey(bbs_models.UserProfile)  #创始人，引用用户表
    brief = models.TextField(max_length=1024,default="nothing...") ##群介绍
    admin = models.ManyToManyField(bbs_models.UserProfile,related_name='group_admins') #管理员
    members = models.ManyToManyField(bbs_models.UserProfile,related_name='group_members') #成员
    members_limit = models.IntegerField(default=200) ##限制成员数量
    def __unicode__(self):
        return self.name

bbs/bbs/views.py
#coding:utf-8

from django.shortcuts import render

# Create your views here.
from django.shortcuts import render,HttpResponse,HttpResponseRedirect
import models
from django.http import Http404
from django.core.exceptions import ObjectDoesNotExist
import  utils
import json
from django.contrib.auth import authenticate,login
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger


# Create your views here.

def account_login(request):
    if request.method == 'GET':  #如果是提交数据
        return  render(request,'login.html')
    else:
        print request.POST
        username = request.POST.get('username')  #获取用户名
        passwd = request.POST.get('password')  #获取密码
        user = authenticate(username=username,password=passwd)   #验证输入的用户名和密码
        if user is not None:  #代表用户的帐号和密码OK
            login(request,user)
            user.userprofile.online = True
            user.userprofile.save()
            return  HttpResponseRedirect("/") #返回到首页
        else:
            return  render(request,'login.html',{  ##如果用户名和密码不正确
                'login_err': "Wrong username or password!"  #打印错误信息
            })


#分页
def index(request):
    article_list = models.Article.objects.all().order_by('-publish_date') #models.Article.objects.all()取出所有，order_by排序，“-”publish_date按降序排列，时间从新到旧，新的在上面
    paginator = Paginator(article_list, 3) # 每1页显示3篇文章
    page = request.GET.get('page')
    try:
        articles = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page.
        articles = paginator.page(1)
    except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
        articles = paginator.page(paginator.num_pages)

    return render(request,'index.html',{
        'articles': articles
    })

def article(request,article_id):
    err_msg = ''
    try:
        article_obj = models.Article.objects.get(id=article_id)
        comments = utils.build_comments_tree(request)
    except ObjectDoesNotExist,e:
        err_msg = str(e)

    return  render(request,'article.html',{
                   'article':article_obj,
                    'err_msg': err_msg,
                    'comments':comments
                    }
                   )


#创建帖子
def create_article(request):
    if request.method == "GET":
        return render(request,'create_article.html')
    elif request.method == 'POST':
        print request.FILES
        bbs_generater = utils.ArticleGen(request)
        res = bbs_generater.create()
        html_ele = '''Your article <<a href="/article/%s/">%s</a>>has been created successfully! ''' %(res.id,res.title)
        return HttpResponse(html_ele)

def life(request):

    return  render(request,'life.html')

def tech(request):

    return  render(request,'tech.html')
def category1024(request):

    return  render(request,'1024.html')

bbs/webqq/views.py
#coding:utf-8
from django.shortcuts import render,HttpResponse
import json,datetime
# Create your views here.
import models
import utils




global_msg_dic = {}  #空的queue
def dashboard(request):
    return render(request,'webqq/dashboard.html')

def send_msg(request):
    print request.POST
    data = request.POST.get('data')
    data = json.loads(data)  #反序列化
    data['date'] =datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S") #打上时间戳
    to_id = data.get('to_id')
    user_obj = models.bbs_models.UserProfile.objects.get(id=to_id)
    contact_type = data.get('contact_type')             #对话类型
    if contact_type == 'single':                        #如果对话类型是single
        if not global_msg_dic.has_key(to_id):           #判断有没有to_id这个queue
            global_msg_dic[to_id] = utils.Chat()         #创建一个queue；在utils里面进行初始化
        global_msg_dic[to_id].msg_queue.put(data)        #如果存在to_id这个queue，就把刚才的消息扔进去
        print '\033[31;1m Push msg [%s] into user [%s] queue' % (data['msg'], user_obj.name)
    elif contact_type == 'group':  #如果对话类型是group
        group_obj = models.QQGroup.objects.get(id=to_id)     #获取到组
        for member in group_obj.members.select_related():    #循环所有的名字
            if member.id != request.user.userprofile.id:     #排除自己
                if not global_msg_dic.has_key(member.id):    #如果没queue
                    global_msg_dic[member.id] = utils.Chat()  #创建queue
                global_msg_dic[member.id].msg_queue.put(data) #把数据放进去queue
                print '\033[31;1m Push msg [%s] into user [%s] queue' % (data['msg'], member.name)

    return HttpResponse("as大苏打")


def get_msg(request):
    uid = request.GET.get('uid') #获取UID
    if uid:  #如果UID获取到
        res = []
        if not global_msg_dic.has_key(uid): ##判断uid在不在消息队列中
            global_msg_dic[uid] = utils.Chat() ##创建一个queue
        res = global_msg_dic[uid].get_msg(request)
        return HttpResponse(json.dumps(res))
    else: #如果uid不为真
        return HttpResponse(json.dumps("uid not provided!")) #返回一个错误信息

bbs/templates/1024.html
{% extends 'index.html' %}


{% block content-left %}

    1024 test

{% endblock %}

{% block content-right %}
    right bar
{% endblock %}

bbs/templates/article.html
{% extends 'index.html' %}
{% load custom %}    <!--载入自定义模版文件-->

{% block content-left %}

   <div class="blog-head">
     <h3>{{ article.title }} </h3>
     <div class="blog-summary-btn">

        <!--<a>{{ article.author.name }} |   </a> {{article.author.name|test_tag}}|{ % test_tag2 article.author.name %}>-->
        <a>{{ article.author.name }} |   </a>
        <span>{{ article.publish_date }}</span>
        <span><i class="fa fa-comment-o"></i>{{ article.comment_set.select_related.count }}</span>
        <span><i class="fa fa-star"></i>{{ article.thumbup_set.select_related.count }}</span>


     </div>
    <div class="blog-content">
     {{ article.content|safe }}

    </div>

    <div class="comments-box">
        {% build_comment_tree comments %}





    </div>
   </div>


{% endblock %}

{% block content-right %}
    right bar
{% endblock %}

bbs/templates/create_article.html
{% extends 'index.html' %}

{% block container %}


<form class="form-horizontal" method="post" action="{% url "create_article" %}" enctype="multipart/form-data">{% csrf_token %}
  <div class="form-group">
    <label  class="col-sm-2 control-label">文章标题</label>
    <div class="col-sm-10">
      <input type="text" class="form-control" name="title" placeholder="标题">
    </div>
  </div>
  <div class="form-group">
    <label class="col-sm-2 control-label">文章简介</label>
    <div class="col-sm-10">
        <textarea class="form-control" rows="3" name="summary"></textarea>
    </div>
  </div>
  <div class="form-group">
    <label  class="col-sm-2 control-label">标题图片</label>
    <div class="col-sm-10">
        <input type="file" name="head_img" />
    </div>
  </div>
  <div class="form-group">
    <label  class="col-sm-2 control-label">内容</label>
    <div class="col-sm-10">
      <textarea id="create_bbs" name="content"></textarea>
    </div>
  </div>

  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <button type="submit" class="btn btn-default">发贴</button>
    </div>
  </div>
</form>

{% endblock %}



{% block bottom-js %}
<script src="/static/plugins/tinymce/js/tinymce/tinymce.min.js"></script>
<script type="text/javascript">

        tinymce.init({
            selector: "#create_bbs",
            theme: "modern",
            //width: 300,
            height: 300,
            plugins: [
                 "advlist autolink link image lists charmap print preview hr anchor pagebreak spellchecker",
                 "searchreplace wordcount visualblocks visualchars code fullscreen insertdatetime media nonbreaking",
                 "save table contextmenu directionality emoticons template paste textcolor"
           ],
           //content_css: "css/content.css",
           toolbar: "insertfile undo redo | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | l      ink image | print preview media fullpage | forecolor backcolor emoticons",
           style_formats: [
                {title: 'Bold text', inline: 'b'},
                {title: 'Red text', inline: 'span', styles: {color: '#ff0000'}},
                {title: 'Red header', block: 'h1', styles: {color: '#ff0000'}},
                {title: 'Example 1', inline: 'span', classes: 'example1'},
                {title: 'Example 2', inline: 'span', classes: 'example2'},
                {title: 'Table styles'},
                {title: 'Table row 1', selector: 'tr', classes: 'tablerow1'}
            ]
        });

</script>

{% endblock %}

bbs/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="blog-summaryor" content="">

    <title>Blog Post - Start Bootstrap Template</title>

    <!-- Bootstrap Core CSS -->
    <link href="/static/css/bootstrap.min.css" rel="stylesheet">

    <link rel="stylesheet" href="/static/font-awesome/css/font-awesome.min.css">
    <!-- Custom CSS -->
    <link href="/static/css/blog-post.css" rel="stylesheet">
    <link href="/static/css/custom_v2.css" rel="stylesheet">
    <link href="/static/css/bootstrap.vertical-tabs.css" rel="stylesheet">


    {% block head-css %}
    {% endblock %}

</head>

<body>

    <!-- Navigation -->
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container">

            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="#">XOXO</a>
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul id="top_menu" class="nav navbar-nav">
                    <li>
                        <a href="/">全部</a>
                    </li>
                    <li>
                        <a href="{% url 'life' %}">生活</a>
                    </li>
                    <li>
                        <a href="{% url 'tech' %}">技术</a>
                    </li>
                    <li>
                        <a href="{% url 'category1024' %}">1024</a>
                    </li>
                    <li>
                        <a href="{% url 'chat' %}">聊天室</a>
                    </li>
                </ul>

                <!--登录部分-->
                <ul class="nav navbar-nav navbar-right">
                    {% if request.user.is_authenticated %}
                    <li>
                        <a href="#">{{request.user.userprofile.name}} </a>
                    </li>
                    <li>
                        <a href="{% url 'create_article' %}">发贴</a>
                    </li>
                    {% else %}
                    <li>
                        <a href="{% url 'login' %}">登录/注册</a>
                    </li>
                    {% endif %}

                </ul>

            </div>
            <!-- /.navbar-collapse -->

        </div>
        <!-- /.container -->
    </nav>

    <!-- Page Content -->
    {% block page-container %}
    <div class="container">
        {% block container %}
        <div class="row">

            <!-- Blog Post Content Column -->
            <div class="col-lg-8">
                {% block content-left %}

                {% for article in articles %}
                 <div class="blog-box row">  <!--加row的意思是让图片单独占一行，否则的话，图片会挤在一起-->
                    <div class="head-img col-md-4">
                        <img  src="/static/{{ article.head_img }}" >
                    </div>
                    <div class="blog-summary-box col-md-8">
                        <h3> <a href="{% url 'article' article.id %}">{{ article.title }}</a></h3>
                        <div class="blog-summary-btn">
                            <a>{{ article.author.name }}</a>
                            <span>{{ article.publish_date }}></span>

                             <span><i class="fa fa-star"></i>3</span> <!--此处就是展示图标的代码-->
                             <span><i class="fa fa-comment-o"></i>6</span> <!--此处就是展示图标的代码-->
                             <span><i class="fa fa-wechat"></i></span> <!--此处就是展示图标的代码-->
                        </div>
                        <div class="blog-summary">
                            {{ article.summary }}
                        </div>
                    </div>
                 </div>

                {% endfor %}


                <!--分页-->
                <div class="pagination">
                <nav>
                  <ul class="pagination">  <!--分页样式-->
                        {% if articles.has_previous %}   <!--如果有上一页-->

                           <li ><a href="?page={{ articles.previous_page_number }}" >上一页</a></li>

                        {% endif %}

                        {% for p_num in articles.paginator.page_range  %}  <!--展现全部页-->
                            {% if p_num == articles.number %}  <!--如果是当前页-->
                                 <li class="active"><a href="?page={{ p_num }}">{{ p_num }}</a></li>
                            {% else %}
                                 <li ><a href="?page={{ p_num }}">{{ p_num }}</a></li>
                            {% endif %}
                        {% endfor %}
                      {% if articles.has_next %}  <!--如果有下一页-->

                               <li ><a href="?page={{ articles.next_page_number }}" >下一页</a></li>

                        {% endif %}
                  </ul>
                </nav>

                </div>



                {% endblock %}
            </div>


            <!-- Blog Sidebar Widgets Column -->
            <div class="col-md-4">
                {% block content-right %}
                <!-- Blog Search Well -->
                <div class="well">
                    <h4>Blog Search</h4>
                    <div class="input-group">
                        <input type="text" class="form-control">
                        <span class="input-group-btn">
                            <button class="btn btn-default" type="button">
                                <span class="glyphicon glyphicon-search"></span>
                        </button>
                        </span>
                    </div>
                    <!-- /.input-group -->
                </div>

                <!-- Blog Categories Well -->
                <div class="well">
                    <h4>Blog Categories</h4>
                    <div class="row">
                        <div class="col-lg-6">
                            <ul class="list-unstyled">
                                <li><a href="#">Category Name</a>
                                </li>
                                <li><a href="#">Category Name</a>
                                </li>
                                <li><a href="#">Category Name</a>
                                </li>
                                <li><a href="#">Category Name</a>
                                </li>
                            </ul>
                        </div>
                        <div class="col-lg-6">
                            <ul class="list-unstyled">
                                <li><a href="#">Category Name</a>
                                </li>
                                <li><a href="#">Category Name</a>
                                </li>
                                <li><a href="#">Category Name</a>
                                </li>
                                <li><a href="#">Category Name</a>
                                </li>
                            </ul>
                        </div>
                    </div>
                    <!-- /.row -->
                </div>

                <!-- Side Widget Well -->
                <div class="well">
                    <h4>Side Widget Well</h4>
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Inventore, perspiciatis adipisci accusamus laudantium odit aliquam repellat tempore quos aspernatur vero.</p>
                </div>
                {% endblock %}
            </div>

        </div>
        <!-- /.row -->

        <hr>
        {% endblock %}
        <!-- Footer -->
        <footer>
            <div class="row">
                <div class="col-lg-12">
                    <p>Copyright &copy; Your Website 2014</p>
                </div>
            </div>
            <!-- /.row -->
        </footer>

    </div>
    {% endblock %}
    <!-- /.container -->

    <!-- jQuery -->
    <script src="/static/js/jquery.js"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="/static/js/bootstrap.min.js"></script>


    {% block bottom-js %}
    <script type="text/javascript">

    </script>

    {% endblock %}







<script type="text/javascript">

//    ｛#鼠标移过变色#｝


    $(document).ready(function(){

        $("#top_menu a").each(function(){

            if ($(this).attr("href") == "{{ request.path }}"){
                $(this).parent().addClass("active");
            };
        });

    });

</script>

</body>

</html>

bbs/templates/life.html
{% extends 'index.html' %}


{% block content-left %}

    生活页

{% endblock %}

{% block content-right %}
    right bar
{% endblock %}

bbs/templates/login.html
{% extends 'index.html' %}

{% block container %}
<div>
    <form method="post" action="{% url 'login' %}">{% csrf_token %}

        <input type="text" name="username" placeholder="username" />
        <input type="password" name="password" placeholder="password" />
        <input type="submit" value="Login" class="btn btn-success" />

    </form>

    <p style="color: red">{{ login_err }}</p>
</div>

{% endblock %}

bbs/templates/tech.html
{% extends 'index.html' %}


{% block content-left %}

    technique

{% endblock %}

{% block content-right %}
    right
{% endblock %}